branch-defaults:
  default:
    environment: udagram-api
  master:
    environment: udagram-api
deploy:
  artifact: ./www/Archive.zip
environment-defaults:
  Udgaramapi-env:
    branch: null
    repository: null
  udagram-api:
    branch: null
    repository: null
global:
  application_name: udgaram-api
  default_ec2_keyname: null
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
